export ARCHS = armv6 armv7 armv7s arm64
export SDKVERSION = 7.1
export TARGET = iphone:clang
export TARGET_IPHONEOS_DEPLOYMENT_VERSION = 3.0
export ADDITIONAL_LDFLAGS = -Wl,-segalign,4000

include Makefile.common
